# Author:  PH01L
# Email:   phoil@osrsbox.com
# Website: https://www.osrsbox.com
#
# Description:
# Docker Compose for osrsbox-api (MongoDB + data loader)
#
# Copyright (c) 2021, PH01L
#
###############################################################################
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################
services:
  mongo:
    container_name: osrsbox-api-mongo
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
    ports:
      - "27017:27017"
    networks:
      - osrs_api
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 12

  data-loader:
    container_name: osrsbox-data-loader
    build:
      context: ./data-loader
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      DATABASE_NAME: osrsbox
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      # Set to true to force reload even if data exists
      FORCE_DATA_LOAD: ${FORCE_DATA_LOAD:-false}
    volumes:
      - ./data-loader:/scripts:ro
    networks:
      - osrs_api
    restart: "no"
    command: /scripts/entrypoint.sh

networks:
  osrs_api:
    driver: bridge
